apiVersion: v1
kind: Pod
metadata:
  name: mysql-volume
spec:
  containers:
  - name: mysql
    image: mysql
    env:
    - name: MYSQL_USER
      value: eazy
    - name: MYSQL_PASSWORD
      value: eazy
    - name: MYSQL_DATABASE
      value: eazytraining
    - name: MYSQL_ROOT_PASSWORD
      value: password
    volumeMounts:
    - name: mysql-data
      mountPath: /var/lib/mysql
  volumes:
  - name: mysql-data
    # chemin du dossier sur l'hôte
    hostPath:
      path: /data-volume
      # ce champ est optionnel
      type: Directory
